[build-system]
requires = [
    "setuptools >= 62.3.0",
    "cython",
    "numpy"
    ]
build-backend = "setuptools.build_meta"

[project]
name = "Alfred-Exoplanets"
dynamic = ["version"]
authors = [{name = "Max Kroft"}]
dependencies = [
    "numpy",
    "matplotlib",
    "emcee",
    "corner",
    "batman-package",   
    "scipy",
    "celerite2",
    "astropy",
    "tqdm",
    "isochrones",
    "svo_filters",
    "setuptools < 81",
    "holoviews",
    "numba",
    "astroquery",
    "mplcursors",
    "pytest"
    ]

[tool.setuptools.dynamic]
version = {attr = "alfred.__version__"}

[tool.setuptools.packages]
find = {}

[tool.setuptools.package-data]
alfred = ["ld_grids/*","example_data/*.csv"]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning"
]